// Mock data for UI development — replace with Supabase queries

export const MOCK_CLIENTS = [
  {
    id: '1',
    name: 'Sunrise Bakery',
    logo: null,
    industry: 'Food & Beverage',
    color: '#f97316',
    accountsCount: 4,
    scheduledPosts: 12,
    status: 'active',
  },
  {
    id: '2',
    name: 'Coastal Fitness',
    logo: null,
    industry: 'Health & Fitness',
    color: '#0693e3',
    accountsCount: 5,
    scheduledPosts: 8,
    status: 'active',
  },
  {
    id: '3',
    name: 'Peak Property Group',
    logo: null,
    industry: 'Real Estate',
    color: '#9b51e0',
    accountsCount: 3,
    scheduledPosts: 5,
    status: 'active',
  },
  {
    id: '4',
    name: 'Green Earth Landscaping',
    logo: null,
    industry: 'Home & Garden',
    color: '#00d084',
    accountsCount: 2,
    scheduledPosts: 3,
    status: 'active',
  },
  {
    id: '5',
    name: 'Metro Dental Clinic',
    logo: null,
    industry: 'Healthcare',
    color: '#0693e3',
    accountsCount: 3,
    scheduledPosts: 0,
    status: 'inactive',
  },
]

export const MOCK_CONNECTED_ACCOUNTS = [
  { id: '1', clientId: '1', platform: 'instagram', username: '@sunrisebakery_au', connected: true, followers: 8420, avatar: null },
  { id: '2', clientId: '1', platform: 'facebook', username: 'Sunrise Bakery', connected: true, followers: 3200, avatar: null },
  { id: '3', clientId: '1', platform: 'tiktok', username: '@sunrisebakery', connected: true, followers: 15800, avatar: null },
  { id: '4', clientId: '1', platform: 'linkedin', username: 'Sunrise Bakery', connected: false, followers: 0, avatar: null },
  { id: '5', clientId: '2', platform: 'instagram', username: '@coastalfitnessau', connected: true, followers: 22100, avatar: null },
  { id: '6', clientId: '2', platform: 'facebook', username: 'Coastal Fitness', connected: true, followers: 9800, avatar: null },
  { id: '7', clientId: '2', platform: 'tiktok', username: '@coastalfitness', connected: true, followers: 41200, avatar: null },
  { id: '8', clientId: '2', platform: 'linkedin', username: 'Coastal Fitness', connected: true, followers: 1400, avatar: null },
  { id: '9', clientId: '2', platform: 'youtube', username: 'Coastal Fitness', connected: true, followers: 5600, avatar: null },
  { id: '10', clientId: '3', platform: 'instagram', username: '@peakpropertygroup', connected: true, followers: 4300, avatar: null },
  { id: '11', clientId: '3', platform: 'facebook', username: 'Peak Property Group', connected: true, followers: 2100, avatar: null },
  { id: '12', clientId: '3', platform: 'linkedin', username: 'Peak Property Group', connected: false, followers: 0, avatar: null },
]

export const MOCK_POSTS = [
  {
    id: '1',
    clientId: '1',
    clientName: 'Sunrise Bakery',
    platforms: ['instagram', 'facebook'],
    content: 'Start your morning right 🌅 Our sourdough loaves are fresh out of the oven. Come grab yours before they sell out!',
    media: [],
    status: 'scheduled',
    scheduledAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    createdBy: 'Sarah Johnson',
  },
  {
    id: '2',
    clientId: '2',
    clientName: 'Coastal Fitness',
    platforms: ['instagram', 'tiktok'],
    content: '5am crew checking in 💪 Who else is smashing their goals this week? Drop a 🔥 below!',
    media: [],
    status: 'published',
    scheduledAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    createdBy: 'Mike Chen',
  },
  {
    id: '3',
    clientId: '1',
    clientName: 'Sunrise Bakery',
    platforms: ['instagram'],
    content: 'This weekend only: Buy 2 croissants, get 1 FREE 🥐 Tag a friend you\'d share this with!',
    media: [],
    status: 'draft',
    scheduledAt: null,
    createdBy: 'Sarah Johnson',
  },
  {
    id: '4',
    clientId: '3',
    clientName: 'Peak Property Group',
    platforms: ['facebook', 'linkedin'],
    content: 'Just listed: A stunning 4-bedroom home in Bondi with panoramic ocean views. Enquire today for an exclusive inspection 🏡',
    media: [],
    status: 'scheduled',
    scheduledAt: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    createdBy: 'Sarah Johnson',
  },
  {
    id: '5',
    clientId: '2',
    clientName: 'Coastal Fitness',
    platforms: ['instagram', 'facebook', 'tiktok'],
    content: 'NEW CLASS ALERT 🚀 HIIT Pilates fusion drops next Monday. Limited spots — book now via the link in bio!',
    media: [],
    status: 'scheduled',
    scheduledAt: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
    createdBy: 'Mike Chen',
  },
]

export const MOCK_ANALYTICS = {
  overview: {
    totalPosts: 284,
    totalReach: 142800,
    totalEngagements: 18940,
    avgEngagementRate: 4.2,
  },
  reachByMonth: [
    { month: 'Sep', reach: 89000 },
    { month: 'Oct', reach: 102000 },
    { month: 'Nov', reach: 118000 },
    { month: 'Dec', reach: 131000 },
    { month: 'Jan', reach: 109000 },
    { month: 'Feb', reach: 127000 },
    { month: 'Mar', reach: 142800 },
  ],
  engagementByPlatform: [
    { platform: 'Instagram', engagement: 8200, color: '#E1306C' },
    { platform: 'TikTok', engagement: 6400, color: '#010101' },
    { platform: 'Facebook', engagement: 2900, color: '#1877F2' },
    { platform: 'LinkedIn', engagement: 1440, color: '#0A66C2' },
  ],
  topPosts: [
    { id: 'p1', client: 'Coastal Fitness', platform: 'tiktok', content: '5am crew checking in 💪', likes: 4820, comments: 312, shares: 891, reach: 48200 },
    { id: 'p2', client: 'Sunrise Bakery', platform: 'instagram', content: 'Buy 2 croissants, get 1 FREE 🥐', likes: 2140, comments: 198, shares: 420, reach: 21400 },
    { id: 'p3', client: 'Peak Property Group', platform: 'facebook', content: 'Just listed: Bondi ocean views 🏡', likes: 890, comments: 64, shares: 280, reach: 12800 },
  ],
}

export const MOCK_STAFF = [
  { id: '1', name: 'Sarah Johnson', email: 'sarah@wordofmouthagency.com.au', role: 'Social Media Manager', avatar: null },
  { id: '2', name: 'Mike Chen', email: 'mike@wordofmouthagency.com.au', role: 'Content Creator', avatar: null },
  { id: '3', name: 'Priya Patel', email: 'priya@wordofmouthagency.com.au', role: 'Account Manager', avatar: null },
]
